version: '3'

services:
  app:
    container_name: test.jochemwhite.nl
    image: test.jochemwhite.nl
    restart: always
    environment:
    - NEXT_PUBLIC_BASE_URL=https://streambuddy.org
    - NEXT_PUBLIC_BACKEND_URL=https://api.streambuddy.org
    - NEXT_PUBLIC_APPWRITE_ENDPOINT=https://appwrite.amrio.nl/v1
    - NEXT_PUBLIC_APPWRITE_PROJECTID=6438fe9e0aa9e66bf3a8
    - NEXT_PUBLIC_APPWRITE_DATABASE_ID=643e77f341e4deeac803
    - NEXT_PUBLIC_APPWRITE_COMMAND_COLLECTION_ID=64392db7f311e52949c5
    - APPWRITE_API_KEY=bb57baee161deead71e4aa1e78e67364db0f132b666652769b32b0d122b0043f0b939c793bdf63ba432570442f6b81e01b7ef8775ae2dbe084fee359df82d04a05bdeba52dd3e6f1f8ccf59a1ce439243fb8375bb3373c79607aefc3f2336b9b91d6b9a2efe7749fd5477580ab579c047892ecb0e3f9eb2b47bef371272745d2
    - NEXT_PUBLIC_TWITCH_CLIENT_ID=0jkqbf5tuyj47uhor15rtnwi5at0s3
    - TWITCH_CLIENT_SECRET=6xfwyr3plu0tb38tdvaykcso3yjoer
    - NEXT_PUBLIC_SPOTIFY_CLIENT_ID=8b783d584d454dc6abbaf00ed64bebad
    - SPOTIFY_CLIENT_SECRET=8ec65ef5aae541859a0fb96789ebffaa

    build:
      dockerfile: Dockerfile
    ports:
      - 3002:3000
