apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-jochemwhite
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-jochemwhite
  template:
    metadata:
      labels:
        app: test-jochemwhite
    spec:
      containers:
      - name: test-jochemwhite
        image: ghcr.io/jochemwhite/test.jochemwhite.nl:d438ff4953c3a182b7fd6aa769264e17cdb6c66e
        ports:
        - containerPort: 3000
