name: Update Package.json Version and Build/Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  update-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Update IMAGE Version
        run: |
          sed -i "s|image: ghcr.io/${{ github.repository }}:.*|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|" kubernetes/deployment.yaml

      - name: Build and push Docker image to GHCR
        run: |
          DOCKER_TAG="ghcr.io/${{ github.repository }}:${{ github.workflow_sha }}"
          docker build -t $DOCKER_TAG .
          docker push $DOCKER_TAG
