name: Update Package.json Version and Build/Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  update-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Login to GitHub Container Registry
      #   run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # - name: Update IMAGE Version
      #   run: |
      #     sed -i "s|image: ghcr.io/${{ github.repository }}:.*|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|" kubernetes/resources/deployment.yaml

      # - name: push updated deployment.yaml
      #   run: |
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git config --global user.name "github-actions[bot]"
      #     git add kubernetes/resources/deployment.yaml
      #     git commit -m "Update deployment.yaml"
      #     git push

      # - name: Build and push Docker image to GHCR
      #   run: |
      #     DOCKER_TAG="ghcr.io/${{ github.repository }}:${{ github.workflow_sha }}"
      #     docker build -t $DOCKER_TAG .
      #     docker push $DOCKER_TAG

      - name: Debug secret value
        run: |
          echo "::set-env name=MY_SECRET::${{ secrets.ARGOCD_API_TOKEN }}"
          echo $MY_SECRET
     
      - name: Deploy to ArgoCD
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://argocd.amrio.nl/api/v1/applications/test-jochemwhite/sync
          method: POST
          customHeaders: |
            Authorization: Bearer ${{ secrets.ARGOCD_API_TOKEN }}
            Content-Type: application/json
          


            
