name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main # You can customize this to your preferred branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      # Check out your repository code.

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      # Set up Docker Buildx for multi-platform builds (not needed for a single platform).

    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      # Log in to GHCR using the GitHub token.

    - name: Build and push Docker image to GHCR
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest .
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest
      # Build and push the Docker image to GHCR.

# Don't forget to create the GITHUB_TOKEN secret in your repository settings.
