name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubernetes
      run: |
        echo "$KUBE_CONFIG" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml

    - name: Build and push Docker image
      run: |
        # Get the GitHub username and repository name dynamically
        GITHUB_USERNAME=$(echo $GITHUB_REPOSITORY | cut -d/ -f1)
        GITHUB_REPO=$(echo $GITHUB_REPOSITORY | cut -d/ -f2)
        
        # Build and push the Docker image
        docker build -t ghcr.io/${GITHUB_USERNAME}/${GITHUB_REPO}/my-image:latest .
        docker push ghcr.io/${GITHUB_USERNAME}/${GITHUB_REPO}/my-image:latest

    - name: Deploy to Kubernetes
      run: kubectl apply -f kubernetes/deployment.yaml -f kubernetes/service.yaml -f kubernetes/ingress.yaml
